#!/bin/ruby

require 'csv'
require 'optparse'
require 'terminal-table'

require_relative 'batting_average'

options = { filters: {} }

OptionParser.new do |opts|
  opts.banner = "Usage: ruby calculate [options]"

  opts.on("--batting_file_path=PATH", "Batting CSV path (./Batting.csv)") do |value|
    options[:batting_file_path] = value
  end

  opts.on("--teams_file_path=PATH", "Teams CSV path (./Teams.csv)") do |value|
    options[:teams_file_path] = value
  end

  opts.on("--filter-year=YEAR", "Filter by Year (1991)") do |value|
    options[:filters][:year] = value if value
  end

  opts.on("--filter-team-name=NAME", "Filter by Team Name ('New York Mets')") do |value|
    options[:filters][:team_name] = value if value
  end
end.parse!

unless options[:batting_file_path]
  puts '--batting_file_path=PATH required! Check: `ruby calculate --help`'

  exit 1
end

unless options[:teams_file_path]
  puts '--teams_file_path=PATH required! Check: `ruby calculate --help`'

  exit 1
end

BattingAverage
  .new(batting_path: options[:batting_file_path], filters: options[:filters], teams_path: options[:teams_file_path])
  .print_table
